openapi: 3.0.1
info:
  title: Python Execute
  description: A plugin that allows the user to run Python code and obtain the output.
  version: v1
servers:
  - url: http://localhost:5003
paths:
  /execute:
    post:
      operationId: executeCode
      summary: Execute Python code and obtain the output
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Python code to execute
                  example: print("Hello, World!")
              required:
                - code
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteCodeResponse'
components:
  schemas:
    ExecuteCodeResponse:
      type: object
      properties:
        output:
          type: string
          description: The output generated by executing the Python code.
